
services:
  postgres:
    image: ankane/pgvector:latest
    container_name: medisync-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: medisync
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - medisync-net

  redis:
    image: redis:latest
    container_name: medisync-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data
    networks:
      - medisync-net

networks:
  medisync-net:
    driver: bridge
